### ISSUE TITLE
It will flash in the first time

### ISSUE THREAD

**Issue by kaka0704** [pkluz/PKRevealController#227]
HomePageViewController *root = [[HomePageViewController alloc] init];
    
    LeftSideMenuViewController *leftMenuViewController = [[LeftSideMenuViewController alloc] init];
    UINavigationController *leftNav = [[UINavigationController alloc] initWithRootViewController:leftMenuViewController];
   
    HTNavigationController* mainNav;
    mainNav = [[HTNavigationController alloc] initWithRootViewController:root];
    self.revealController=[PKRevealController revealControllerWithFrontViewController:mainNav
                                                                   leftViewController:leftNav];
    self.revealController.animationDuration = 0.25;
        self.window.rootViewController = self.revealController;

top are  my all codes
when I  call  [self.navigationController.revealController showViewController:self.navigationController.revealController.leftViewController]; 
in the first time
it will flash ,how can fix this?

**Comment by pkluz** [comment]
See #181
