### ISSUE TITLE
setFrontViewController deprecated, no replacement

### ISSUE THREAD

**Issue by d370urn3ur** [pkluz/PKRevealController#244]
The documentation is incorrect for `setFrontViewController:focusAfterChange:completion:`.  It says 

> Deprecated because unnecessary. Functionality can be reproduced by calling showViewController:animated:completion

However, showViewController: does not reproduce the functionality of setFrontViewController.  setFront exchanges the front view controller with the new one passed in as the parameter, showViewController doesn't replace the front view controller, it just animates the opening / closing of the side views.

Why is setFrontViewController deprecated?  I don't see any other method that can replace this critical functionality.

**Comment by stuberm** [comment]
Just set the front view controller before calling `show`.

```
revealViewController.frontViewController = viewController
revealViewController.show(viewController)
```
