### ISSUE TITLE
PKReveal dead?

### ISSUE THREAD

**Issue by d370urn3ur** [pkluz/PKRevealController#245]
Is this project dead?  64 open issues and the last commit was over a year ago?  Does anyone know of an alternative?

**Comment by adonoho** [comment]
This project is actively used by many people, myself included. Not all projects need constant developmental churn. It works well at what it does. There are many alternative projects.

**Comment by pkluz** [comment]
I'm most definitely not doing the best work in day-to-day operations of maintaining `PKRevealController`, nevertheless in general I consider it to be in fairly decent shape and fairly feature complete as @adonoho already explained. Some things don't need "more and more features" to do their job.

However, there's a few things that I intend to tackle on the horizon.

**Comment by DoctorG** [comment]
I use this library and its great! Appreciate your hard work and sharing for myself and others!

Gregory P. Moore, MD
James River Ob/Gyn
7101 Jahnke Road, Suite 280
Richmond, VA 23225
804-272-5508
JamesRiverObGyn.com (http://www.jamesriverobgyn.com)
