### ISSUE TITLE
development branch: tap recognizer breaks uitableview cell selection in frontview 

### ISSUE THREAD

**Issue by ekurutepe** [pkluz/PKRevealController#76]
I've inserted a `UINavigationViewController` with a `UITableViewController` as the `topViewController` and saw that the default `PKRevealController` tap recognizer interferes with the table view selection. 

I have a fix that I can submit as a pull request if you wish.

**Comment by vergaramikel** [comment]
Hi, I solved the issue as explained in the FAQ, but I also wanted to have the "show left menu" gesture active. So I did the following:

In the frontViewController: viewDidLoad

    //Add a right swipe gesture recognizer
    UISwipeGestureRecognizer *recognizer = [[UISwipeGestureRecognizer alloc] initWithTarget:self
                                                                                     action:@selector(showLeftMenu)];
    recognizer.delegate = self;
    [recognizer setDirection:(UISwipeGestureRecognizerDirectionRight)];
    [self.tableController.tableView addGestureRecognizer:recognizer];


-(void)showLeftMenu{
    if (self.revealController.state == PKRevealControllerShowsFrontViewController) {
        [self.revealController showViewController:self.revealController.leftViewController];
    }
}

Hope you find it useful

**Comment by Skornos** [comment]
@vergaramikel great solution, it is the only one which actually works for me. Did you implement even hideLeftMenu to hide menu on swipe when is revealed?

**Comment by Skornos** [comment]
ok, i'll put my two cents in.

in TableViewController.h add <UIGestureRecognizerDelegate>
and in TableViewController.m
```objective-c
-(void)viewWillAppear:(BOOL)animated{
self.revealController.revealPanGestureRecognizer.delegate = self;
}

- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
{
    if (self.tableView.editing)
        return NO;
    else
        return YES;
}
```

this way it doesn't interfere with uitableviewcell delete gesture
